# Use a Node.js image as the base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY ./package.json ./

# Install frontend dependencies
RUN npm install

# Copy your frontend code to the container
COPY . .

# Expose the port your frontend app will run on (if needed)
# EXPOSE 3000

# Start your frontend application
CMD ["npm", "start"]
