name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Check Current User
      run: whoami

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        # Commands to deploy to VPS
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'ENDSSH'
        cd ArivaPay
        git pull origin main
        docker-compose up --build -d
        ENDSSH
